# Machine Learning
## Numpy

In [1]:
# Numpy 불러오기
import numpy as np

In [2]:
# 매장 A와 B의 3, 4, 5월의 매출
# list에 저장
store_a = [20, 10, 30]
store_b = [70, 90, 70]

In [3]:
# 리스트의 합
list_sum = store_a + store_b
list_sum

[20, 10, 30, 70, 90, 70]

In [4]:
# 리스트를 넘파이 array로 변환
np_store_a = np.array(store_a)
np_store_b = np.array(store_b)

In [5]:
array_sum = np_store_a + np_store_b
array_sum

array([ 90, 100, 100])

In [6]:
np_store_a.shape, np_store_a.ndim, np_store_a.itemsize, np_store_a.size

((3,), 1, 4, 3)

In [7]:
# 2차원 배열
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# np_store_a = [20, 10, 30], np_store_b = [70, 90, 70]
sub = np_store_a - np_store_b
mul = np_store_a * np_store_b
div = np_store_a / np_store_b
sub, mul, div

(array([-50, -80, -40]),
 array([1400,  900, 2100]),
 array([0.28571429, 0.11111111, 0.42857143]))

In [14]:
np.eye(4) * 10

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])