# Machine Learning Assignment 1

In [2]:
import numpy as np

In [3]:
# 3.1 1)
a = np.arange(1, 46)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]


In [37]:
# 3.1 2)
np.random.seed(85)
lotto = np.arange(1, 86)
np.random.shuffle(lotto)
print("lotto = ", lotto[:6])

lotto =  [70 30 78 72 11 49]


In [38]:
# 3.1 3)
selected_lotto = lotto[:6]
sorted_lotto = np.sort(selected_lotto)
print("lotto = ", sorted_lotto[:6], ", 추가 번호 = ", lotto[6])

lotto =  [11 30 49 70 72 78] , 추가 번호 =  57


In [20]:
# 3.1 4)
n_arr = np.arange(25).reshape(5,5)
print(n_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [21]:
# 3.1 5)
first_n_arr = n_arr[0,0]
last_n_arr = n_arr[4,4]
print("첫 원소: ", first_n_arr)
print("마지막 원소 : ", last_n_arr)

첫 원소:  0
마지막 원소 :  24


In [22]:
# 3.1 6)
slicing1_n_arr = n_arr[0:2]
print(slicing1_n_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [24]:
# 3.1 7)
slicing2_n_arr = n_arr[:,::2]
print(slicing2_n_arr)

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]]


In [26]:
# 3.1 8)
slicing3_n_arr = n_arr[0:2].reshape(5,2)
print(slicing3_n_arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [29]:
# 3.2
np.random.randn(2,2,2)

array([[[-0.72568362, -0.94585816],
        [ 0.68946224,  0.08587416]],

       [[-0.38202431,  0.16045109],
        [ 0.76483333,  1.18209444]]])

In [5]:
# 3.2 1)
a = np.random.randn(2,2,2)
print("a 배열의 최대값 : ", a.max())

a 배열의 최대값 :  1.3486587953167646


In [6]:
# 3.2 1)
a = np.random.randn(2,2,2)
print("a 배열의 최소값 : ", a.min())

a 배열의 최소값 :  -1.4468202061232702


In [12]:
# 3.3
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10,],
              [11, 12, 13, 14, 15]])
# 1)
print(a[:,1:])

# 2)
print(a[0:1,0:2])

# 3)
print(a[::2,::2])

[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]
[[1 2]]
[[ 1  3  5]
 [11 13 15]]


In [15]:
# 3.4 1)
a = np.arange(1,26).reshape(5,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [18]:
# 3.4 2)
sum_a = np.sum(a, axis = 0)
print(행렬의 행 방향 성분의 합:  sum_a)

array([55, 60, 65, 70, 75])