# 2025.03.18

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])


In [3]:
a[1:]

array([2, 3])

In [4]:
a[0:2]

array([1, 2])

In [7]:
a = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])

In [8]:
# Q1: [[2, 3], [6, 7]]
# Q2: [[6, 7], [10, 11]]

In [11]:
# A1:
a[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [16]:
# A2:
a[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [18]:
# 3차원:(깊이, 행, 열)
z = np.arange(36).reshape(3,4,3)
z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [19]:
z[1, 0:2, 1:]

array([[13, 14],
       [16, 17]])

In [21]:
z[2, 2:, 0:]

array([[30, 31, 32],
       [33, 34, 35]])

In [23]:
sum_a = np.sum(a)
sum_a

78

In [24]:
sum_axis0 = np.sum(a, axis = 0)
sum_axis0

array([15, 18, 21, 24])

In [25]:
sum_axis1 = np.sum(a, axis = 1)
sum_axis1

array([10, 26, 42])

In [30]:
## 3차원 원소의 합
sum_z = np.sum(z)
sum_z

630

In [33]:
sum_z2 = np.sum(z, axis = 2)
sum_z2

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

In [32]:
sum_z2.shape

(3, 4)

In [35]:
# axis = 0
sum_z0 = np.sum(z, axis=0)
print(sum_z0.shape, sum_z0)

(4, 3) [[36 39 42]
 [45 48 51]
 [54 57 60]
 [63 66 69]]


In [36]:
# axis = 1
sum_z1 = np.sum(z, axis=1)
print(sum_z1.shape, sum_z1)

(3, 3) [[ 18  22  26]
 [ 66  70  74]
 [114 118 122]]


In [40]:
# 난수 (random)
np.random.rand(5) # 실수0~1

array([0.60350382, 0.26747783, 0.87483395, 0.05139607, 0.92378991])

In [42]:
np.random.randint(150, 200, size = 5)

array([169, 194, 191, 199, 169])

In [43]:
# 평균값이 165, 표준편차가 10인 값을 5개 생성
# 표준정규분포 : 평균이 0, 표준편차가 1인 데이터의 분포
rnd = np.random.randn(5) * 10 + 165
rnd

array([158.16815786, 157.44221053, 162.16086752, 159.19909839,
       174.64754053])

In [44]:
rnd.round(2)

array([158.17, 157.44, 162.16, 159.2 , 174.65])

In [45]:
rnd.round(1)

array([158.2, 157.4, 162.2, 159.2, 174.6])

In [47]:
#정수형 변환
rnd.astype(int)

array([158, 157, 162, 159, 174])

In [50]:
nums = np.random.normal(loc = 165, scale = 10, size = (3,4)).round(2)
nums

array([[164.12, 172.17, 175.85, 164.49],
       [175.63, 160.05, 162.03, 169.19],
       [164.99, 164.01, 178.79, 156.42]])

In [53]:
# 값 섞기
a = np.arange(10)
print("shuffle 전: ", a)
np.random.shuffle(a)
print("shuffle 후: ", a)

shuffle 전:  [0 1 2 3 4 5 6 7 8 9]
shuffle 후:  [2 5 0 4 6 3 8 9 1 7]


In [64]:
# numpy 평균
a = np.array([10, 20, 30, 40, 50])
print("a 평균: ", a.mean())
print("a 분산: ", a.var())
print("a 표준편차: ", a.std())

a 평균:  30.0
a 분산:  200.0
a 표준편차:  14.142135623730951


In [60]:
"""
Q3
arr = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]
Q3-1 : arr의 평균, 분산, 표준편차를 구하시오.
Q3-2 : arr의 행의 평균, 분산, 표준편차를 구하시오.
Q3-3 : arr의 열의 평균, 분산, 표준편차를 구하시오.
"""

'\nQ3\narr = [[1, 2, 3, 4],\n       [5, 6, 7, 8],\n       [9, 10, 11, 12]]\nQ3-1 : arr의 평균, 분산, 표준편차를 구하시오.\nQ3-2 : arr의 행의 평균, 분산, 표준편차를 구하시오.\nQ3-3 : arr의 열의 평균, 분산, 표준편차를 구하시오.\n'

In [82]:
# A3-1 전체
arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
print("arr의 평균: ", arr.mean())
print("arr의 분산: ", arr.var())
print("arr의 표준편차: ", arr.std())

arr의 평균:  6.5
arr의 분산:  11.916666666666666
arr의 표준편차:  3.452052529534663


In [78]:
# A3-2 행
arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
print("arr의 행의 평균: ", arr.mean(axis=1))
print("arr의 행의 분산: ", arr.var(axis=1))
print("arr의 행의 표준편차: ", arr.std(axis=1))

arr의 행의 평균:  [ 2.5  6.5 10.5]
arr의 행의 분산:  [1.25 1.25 1.25]
arr의 행의 표준편차:  [1.11803399 1.11803399 1.11803399]


In [84]:
# A3-3 열
arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
print("arr의 열의 평균: ", arr.mean(axis=0))
print("arr의 열의 분산: ", arr.var(axis=0))
print("arr의 열의 표준편차: ", arr.std(axis=0))

arr의 열의 평균:  [5. 6. 7. 8.]
arr의 열의 분산:  [10.66666667 10.66666667 10.66666667 10.66666667]
arr의 열의 표준편차:  [3.26598632 3.26598632 3.26598632 3.26598632]
